/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pages` | `/pages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/debts` | `/home/debts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/sales` | `/home/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/stock` | `/home/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/components/scan` | `/home/components/scan`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pages` | `/pages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/debts` | `/home/debts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/sales` | `/home/sales`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/stock` | `/home/stock`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/components/scan` | `/home/components/scan`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pages${`?${string}` | `#${string}` | ''}` | `/pages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/debts${`?${string}` | `#${string}` | ''}` | `/home/debts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/sales${`?${string}` | `#${string}` | ''}` | `/home/sales${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/stock${`?${string}` | `#${string}` | ''}` | `/home/stock${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/components/scan${`?${string}` | `#${string}` | ''}` | `/home/components/scan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pages` | `/pages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/debts` | `/home/debts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/sales` | `/home/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/stock` | `/home/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/components/scan` | `/home/components/scan`; params?: Router.UnknownInputParams; };
    }
  }
}
